### ISSUE TITLE
problem with installing pkg64  and desktop

### ISSUE THREAD

**Issue by RabsK** [CTSRD-CHERI/cheribsd-ports#100]
Dear researcher/technical team,

Hope this message will find you well!

I have been trying for a couple of months to install desktop for cheribsd. Unfortunately, I am unable to install it. It may be because of the pkg64c and pkg64 package.

<img width="546" alt="image" src="https://github.com/CTSRD-CHERI/cheribsd-ports/assets/49935520/ac0f0d72-14de-4e77-8369-76ba927f00bc">
<img width="279" alt="image" src="https://github.com/CTSRD-CHERI/cheribsd-ports/assets/49935520/35bca6f7-77c9-4e4a-931c-6d41f01ad35b">

I have tried after installing the cheribsd using pkg64 and during the installation of OS as well.

Please let me know if there is an alternative to this.

Thank you
Regards

**Comment by kwitaszczyk** [comment]
The error says that the name `pkg.CheriBSD.org` cannot be resolved. It looks like a networking issue in your configuration. Could you make sure that you have correctly configured network?

**Comment by RabsK** [comment]
Thank you for your reply.

Yes, I am using only internet connection provided and configured by IT department. Unless there is something that needs to be configured within the board after or before installing CheriBSD. If there is a method to configure network using CheriBSD then please let me know.

Thank you

**Comment by kwitaszczyk** [comment]
Does your DNS server respond (e.g., `ping 8.8.8.8`) and resolve the pkg.CheriBSD.org name (e.g., `host pkg.cheribsd.org`)?

`ifconfig` should print a valid IP address, `netstat -rn` should print a valid gateway address and `/etc/resolv.conf` should include a valid DNS server address. The CheriBSD installer should ask you about all these settings and set them for you. You can read more how to manually configure network on a FreeBSD/CheriBSD host in the [FreeBSD handbook](https://docs.freebsd.org/en/books/handbook/network/#config-network-connection) .
