### ISSUE TITLE
www/chromium: build an aarch64 package

### ISSUE THREAD

**Issue by paulmetzger** [CTSRD-CHERI/cheribsd-ports#11]
Hello,

It would be great if we could add Chromium to the CheriBSD ports. I am interested in this in the context of the Chrompartments project, which will start soon. As the name suggests, the project will compartmentalise the Chromium webbrowser.
However, adding a widely used modern webbrowser to the CheriBSD desktop would be beneficial independent of Chrompartments.
See https://www.chromium.org/chromium-projects/ for more information on Chromium.
Building Chromium for aarch64 instead of purecap is probably an easier first step. It might be possible to turn off some features initially to reduce engineering effort.

At the moment poudriere fails to build fontconfig, which is one of Chromium's dependencies: https://poudriere.cheribsd.org/hosts/freebsd-arm64/data/cheribsd-aarch64-main/2022-04-27_15h53m08s/logs/errors/fontconfig-2.13.94_2,1.log
The build fails because a bug in clang is triggered.
@arichardson and @bukinr built fontconfig as purecap and hybrid library with this: https://gitlab.freedesktop.org/arichardson/fontconfig

Best regards,
Paul

**Comment by paulmetzger** [comment]
@kwitaszczyk fixed the fontconfig issue.
Now the rust, which is another dependency of Chromium, fails: https://poudriere.cheribsd.org/hosts/freebsd-arm64/build.html?mastername=cheribsd-aarch64-main&build=2022-06-06_10h49m17s

**Comment by kwitaszczyk** [comment]
A package for the 20220828 CheriBSD ABI version was published with CheriBSD 22.12.
