### ISSUE TITLE
sysutils/u-boot-bhyve-arm64: Need multiple vCPUs patch for release

### ISSUE THREAD

**Issue by jrtc27** [CTSRD-CHERI/cheribsd-ports#135]
See https://github.com/CTSRD-CHERI/cheribsd/pull/1958 / https://reviews.freebsd.org/D42995

**Comment by jrtc27** [comment]
Just committed by Mark as bd62eb84db62 upstream.

**Comment by kwitaszczyk** [comment]
u-boot-bhyve-arm64-2023.07.02_1 is available now.
