### ISSUE TITLE
security/sudo: In-address space security exception with read-only root file system

### ISSUE THREAD

**Issue by kwitaszczyk** [CTSRD-CHERI/cheribsd-ports#26]
@bukinr reported that sudo crashes with a CHERI exception when trying to remount a read-only root file system:
```
$ sudo mount -o rw /
In-address space security exception
```
After changing a root file system entry in fstab to `rw`, the issue is gone.

**Comment by rwatson** [comment]
In multiuser mode, logged in via SSH as a non-root user, I see:
```
robert@cheri-blossom:~ % sudo echo hi

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password:
In-address space security exception
```

But, investigating, this appears to be a property of having my password field in /etc/master.passwd be “*”.

Further, I wonder if it might be a PAM issue rather than a sudo issue, as passwd(1) gives the following in the same situation:
```
robert@cheri-blossom:~ % passwd
Changing local password for robert
Old Password:
In-address space security exception
```

With a password set, no problem:
```
robert@cheri-blossom:~ % passwd
Changing local password for robert
Old Password:
New Password:
Retype New Password:
```

So I wonder if this is about “*” processing rather than about sudo, as well.

Tagging @brooksdavis, as probably we will want to file a CheriBSD issue.

**Comment by kwitaszczyk** [comment]
With `*` as root password, `su` also fails:
```
kw543@morello7-dev:~ $ su
Password:
In-address space security exception
kw543@morello7-dev:~ $ 
```

**Comment by kwitaszczyk** [comment]
This is what I get when I do:
1. Run `su` and don't type in anything:
    ```
    kw543@morello7-dev:~ $ su
    Password:
    ```
2. As root, attach to the process with gdb with execute `continue`.
3. Press Enter in `su`.
4. gdb receives SIGPROT:
    ```
    Program received signal SIGPROT, CHERI protection violation
    Capability tag fault.
    _rtld_tlsdesc_dynamic () at /local/scratch/jenkins/workspace/CheriBSD-pipeline_main/cheribsd/libexec/rtld-elf/aarch64/rtld_start.S:234
    234     /local/scratch/jenkins/workspace/CheriBSD-pipeline_main/cheribsd/libexec/rtld-elf/aarch64/rtld_start.S: No such file or directory.
    (gdb) 
    ```

**Comment by bsdjhb** [comment]
Probable fix at https://github.com/CTSRD-CHERI/cheribsd/pull/1429 (thanks to @jrtc27 for sleuthing)

**Comment by bsdjhb** [comment]
Can someone confirm this is now fixed on `dev`?
